version: '3'

services:
  backend:
    build:
      context: ./backend
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DATABASE_HOST=localhost
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=home123
      - DATABASE_NAME=media_scrapper
      - PUPPETEER_NUMBER_OF_PAGE_PER_BROWSER=10
      - JWT_SECRET=thisisasamplesecret
      - JWT_ACCESS_EXPIRATION_MINUTES=30
      - JWT_REFRESH_EXPIRATION_DAYS=30
    ports:
      - '3000:3000'
    restart: on-failure
    volumes:
      - ./backend:/usr/src/app
    networks:
      - node-network

  frontend:
    build:
      context: ./frontend
    ports:
      - '3001:80'
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - node-network

  db:
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: media_scrapper
    ports:
      - '3306:3306'
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
